export const partidos = [
  {
    id: 1,
    equipo1: "Argentina",
    equipo2: "Canadá",
    resultado: "1 - 0",
    fase: "De grupos",
    fecha: "20/06/2024",
    estadio: "Mercedes-Benz Stadium, Atlanta",
    titulares: ["Ángel Di María", "Lionel Messi", "Emiliano Martínez"],
    goleadores: ["Julián Álvarez", "Lautaro Martínez"],
  },
  {
    id: 2,
    equipo1: "Chile",
    equipo2: "Argentina",
    resultado: "0 - 1",
    fase: "De grupos",
    fecha: "25/06/2024",
    estadio: "MetLife Stadium, East Rutherford",
    titulares: ["Ángel Di María", "Lionel Messi", "Emiliano Martínez"],
    goleadores: ["Lautaro Martínez"],
  },
  {
    id: 3,
    equipo1: "Argentina",
    equipo2: "Perú",
    resultado: "2 - 0",
    fase: "De grupos",
    fecha: "29/06/2024",
    estadio: "Hard Rock Stadium, Miami",
    titulares: ["Ángel Di María", "Lionel Messi", "Emiliano Martínez"],
    goleadores: ["Lautaro Martínez"]
  },
  {
    id: 4,
    equipo1: "Argentina",
    equipo2: "Ecuador",
    resultado: "1 - 1",
    fase: "Cuartos de final",
    fecha: "04/07/2024",
    estadio: "NRG Stadium, Houston",
    titulares: ["Ángel Di María", "Lionel Messi", "Emiliano Martínez"],
    goleadores: ["Lisandro Martínez"],
    penales: [
      { jugador: "Messi", resultado: "Fallo (travesaño)" },
      { jugador: "Álvarez", resultado: "Acierto" },
      { jugador: "Mac Allister", resultado: "Acierto" },
      { jugador: "Montiel", resultado: "Acierto" },
      { jugador: "Otamendi", resultado: "Acierto" },
      { jugador: "Mena", resultado: "Fallo (atajado)" },
      { jugador: "Minda", resultado: "Fallo (atajado)" },
      { jugador: "Yeboah", resultado: "Acierto" },
      { jugador: "J. Caicedo", resultado: "Acierto" }
    ]
  },
  {
    id: 5,
    equipo1: "Argentina",
    equipo2: "Canadá",
    resultado: "2 - 0",
    fase: "Semifinales",
    fecha: "09/07/2024",
    estadio: "MetLife Stadium, East Rutherford",
    titulares: ["Ángel Di María", "Lionel Messi", "Emiliano Martínez"],
    goleadores: ["Julián Álvarez", "Lionel Messi"]
  },
  {
    id: 6,
    equipo1: "Argentina",
    equipo2: "Colombia",
    resultado: "1 - 0",
    fase: "Final",
    fecha: "14/07/2024",
    estadio: "Hard Rock Stadium, Miami",
    titulares: ["Ángel Di María", "Lionel Messi", "Emiliano Martínez"],
    goleadores: ["Lautaro Martínez"]
  },
];
