export const jugadoresArgentina = [
    {
        nombre: "Emiliano Martínez",
        posicion: "Portero",
        edad: 31,
        estatura: 195,
        peso: 88,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 26,
        goles: 0,
        asistencias: 0,
        tarjetasAmarillas: 1,
        tarjetasRojas: 0,
        foto: "/img/jugadores/dibu.jpg",
    },
    {
        nombre: "Gonzalo Montiel",
        posicion: "Defensa",
        edad: 26,
        estatura: 175,
        peso: 70,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 40,
        goles: 1,
        asistencias: 3,
        tarjetasAmarillas: 6,
        tarjetasRojas: 0,
        foto: "/img/jugadores/montiel.jpg",
    },
    {
        nombre: "Nahuel Molina",
        posicion: "Defensa",
        edad: 25,
        estatura: 175,
        peso: 70,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 25,
        goles: 2,
        asistencias: 4,
        tarjetasAmarillas: 3,
        tarjetasRojas: 0,
        foto: "/img/jugadores/molina.jpg",
    },
    {
        nombre: "Cristian Romero",
        posicion: "Defensa",
        edad: 25,
        estatura: 185,
        peso: 79,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 23,
        goles: 1,
        asistencias: 1,
        tarjetasAmarillas: 5,
        tarjetasRojas: 0,
        foto: "/img/jugadores/romero.jpg",
    },
    {
        nombre: "Nicolás Otamendi",
        posicion: "Defensa",
        edad: 35,
        estatura: 183,
        peso: 82,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 100,
        goles: 4,
        asistencias: 3,
        tarjetasAmarillas: 18,
        tarjetasRojas: 1,
        foto: "/img/jugadores/otamendi.jpg",
    },
    {
        nombre: "Lisandro Martínez",
        posicion: "Defensa",
        edad: 25,
        estatura: 175,
        peso: 77,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 20,
        goles: 0,
        asistencias: 1,
        tarjetasAmarillas: 2,
        tarjetasRojas: 0,
        foto: "/img/jugadores/lisandro_martinez.jpg",
    },
    {
        nombre: "Marcos Acuña",
        posicion: "Defensa",
        edad: 31,
        estatura: 172,
        peso: 69,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 45,
        goles: 0,
        asistencias: 5,
        tarjetasAmarillas: 7,
        tarjetasRojas: 0,
        foto: "/img/jugadores/acuña.jpg",
    },
    {
        nombre: "Leandro Paredes",
        posicion: "Centrocampista",
        edad: 29,
        estatura: 180,
        peso: 75,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 52,
        goles: 4,
        asistencias: 5,
        tarjetasAmarillas: 11,
        tarjetasRojas: 1,
        foto: "/img/jugadores/paredes.jpg",
    },
    {
        nombre: "Rodrigo De Paul",
        posicion: "Centrocampista",
        edad: 29,
        estatura: 180,
        peso: 70,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 52,
        goles: 2,
        asistencias: 9,
        tarjetasAmarillas: 10,
        tarjetasRojas: 0,
        foto: "/img/jugadores/de_paul.jpg",
    },
    {
        nombre: "Giovani Lo Celso",
        posicion: "Centrocampista",
        edad: 27,
        estatura: 177,
        peso: 68,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 40,
        goles: 2,
        asistencias: 8,
        tarjetasAmarillas: 4,
        tarjetasRojas: 0,
        foto: "/img/jugadores/lo_celso.png",
    },
    {
        nombre: "Enzo Fernández",
        posicion: "Centrocampista",
        edad: 22,
        estatura: 178,
        peso: 75,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 15,
        goles: 1,
        asistencias: 2,
        tarjetasAmarillas: 3,
        tarjetasRojas: 0,
        foto: "/img/jugadores/enzo_fernandez.jpg",
    },
    {
        nombre: "Alexis Mac Allister",
        posicion: "Centrocampista",
        edad: 24,
        estatura: 174,
        peso: 72,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 20,
        goles: 1,
        asistencias: 3,
        tarjetasAmarillas: 2,
        tarjetasRojas: 0,
        foto: "/img/jugadores/mac_callister.jpg",
    },
    {
        nombre: "Lionel Messi",
        posicion: "Delantero",
        edad: 36,
        estatura: 170,
        peso: 72,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 172,
        goles: 96,
        asistencias: 50,
        tarjetasAmarillas: 8,
        tarjetasRojas: 1,
        foto: "/img/jugadores/messi.jpg",
    },
    {
        nombre: "Ángel Di María",
        posicion: "Delantero",
        edad: 36,
        estatura: 180,
        peso: 75,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 132,
        goles: 27,
        asistencias: 23,
        tarjetasAmarillas: 9,
        tarjetasRojas: 0,
        foto: "/img/jugadores/di_maria.jpg",
    },
    {
        nombre: "Lautaro Martínez",
        posicion: "Delantero",
        edad: 27,
        estatura: 174,
        peso: 72,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 68,
        goles: 30,
        asistencias: 23,
        tarjetasAmarillas: 9,
        tarjetasRojas: 0,
        foto: "/img/jugadores/lautaro_martinez.jpg",
    },
    {
        nombre: "Julián Álvarez",
        posicion: "Delantero",
        edad: 23,
        estatura: 170,
        peso: 70,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 20,
        goles: 7,
        asistencias: 3,
        tarjetasAmarillas: 2,
        tarjetasRojas: 0,
        foto: "/img/jugadores/julian_alvarez.jpg",
    },
    {
        nombre: "Paulo Dybala",
        posicion: "Delantero",
        edad: 30,
        estatura: 177,
        peso: 75,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 34,
        goles: 3,
        asistencias: 5,
        tarjetasAmarillas: 4,
        tarjetasRojas: 0,
        foto: "/img/jugadores/dybala.jpg",
    },
    {
        nombre: "Nicolás González",
        posicion: "Delantero",
        edad: 25,
        estatura: 180,
        peso: 72,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 20,
        goles: 4,
        asistencias: 2,
        tarjetasAmarillas: 3,
        tarjetasRojas: 0,
        foto: "/img/jugadores/nicolas_gonzalez.jpeg",
    },
    {
        nombre: "Germán Pezzella",
        posicion: "Defensa",
        edad: 32,
        estatura: 187,
        peso: 82,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 30,
        goles: 2,
        asistencias: 1,
        tarjetasAmarillas: 5,
        tarjetasRojas: 0,
        foto: "/img/jugadores/german.jpg",
    },
    {
        nombre: "Juan Foyth",
        posicion: "Defensa",
        edad: 25,
        estatura: 187,
        peso: 78,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 15,
        goles: 0,
        asistencias: 1,
        tarjetasAmarillas: 3,
        tarjetasRojas: 0,
        foto: "/img/jugadores/foyth.jpg",
    },
    {
        nombre: "Exequiel Palacios",
        posicion: "Centrocampista",
        edad: 25,
        estatura: 177,
        peso: 70,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 20,
        goles: 1,
        asistencias: 2,
        tarjetasAmarillas: 2,
        tarjetasRojas: 0,
        foto: "/img/jugadores/palacios.jpg",
    },
    {
        nombre: "Guido Rodríguez",
        posicion: "Centrocampista",
        edad: 29,
        estatura: 185,
        peso: 80,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 25,
        goles: 1,
        asistencias: 1,
        tarjetasAmarillas: 4,
        tarjetasRojas: 0,
        foto: "/img/jugadores/guido.jpg",
    },
    {
        nombre: "Nicolás Tagliafico",
        posicion: "Defensa",
        edad: 31,
        estatura: 172,
        peso: 65,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 45,
        goles: 1,
        asistencias: 3,
        tarjetasAmarillas: 6,
        tarjetasRojas: 0,
        foto: "/img/jugadores/tagliafico.jpg",
    },
    {
        nombre: "Franco Armani",
        posicion: "Portero",
        edad: 37,
        estatura: 189,
        peso: 85,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 18,
        goles: 0,
        asistencias: 0,
        tarjetasAmarillas: 1,
        tarjetasRojas: 0,
        foto: "/img/jugadores/armani.jpeg",
    },
    {
        nombre: "Thiago Almada",
        posicion: "Centrocampista",
        edad: 22,
        estatura: 171,
        peso: 63,
        nacionalidad: "Argentina",
        bandera: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
        partidos: 10,
        goles: 1,
        asistencias: 1,
        tarjetasAmarillas: 1,
        tarjetasRojas: 0,
        foto: "/img/jugadores/thiago.jpg",
    },
];